/**
 * Typed wrapper around Tauri's `invoke`.
 *
 * All Rust command I/O should flow through this module. When we wire up
 * `specta` / `ts-rs` in M1, replace the hand-typed commands map with
 * generated types so the command surface is single-sourced from Rust.
 *
 * See CLAUDE.md §7 (TS conventions) + §12 (definition of done).
 */
import { invoke as rawInvoke } from "@tauri-apps/api/core";

// Hand-typed for now — will be generated by specta in M1.
export interface CommandMap {
  altr_version: { args: undefined; ret: string };
  ping: { args: undefined; ret: "pong" };
}

export async function invoke<K extends keyof CommandMap>(
  cmd: K,
  args?: CommandMap[K]["args"],
): Promise<CommandMap[K]["ret"]> {
  return rawInvoke(cmd, args as Record<string, unknown> | undefined) as Promise<
    CommandMap[K]["ret"]
  >;
}
